[package]
name = "example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
postcard-forth = { path = "../postcard-forth" }
postcard-forth-derive = { path = "../postcard-forth-derive" }
