//! Generated by `stress-gen` - do not edit!

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000000;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000001 {
    field00: i8,
    field01: u8,
    field02: u16,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000002(usize, i64, usize, isize, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000003(i8, u32, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000004 {
    field00: isize,
    field01: i8,
    field02: i8,
    field03: u8,
    field04: i128,
}

/// generated
type GenTup00000005 = (GenTupStruct00000003, u8, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000006 {
    VarEmpty00,
    VarNewTy01(usize),
    VarStruct02 {
        field00: i128,
        field01: u64,
        field02: bool,
    },
    VarTuple03(i8, isize, ),
    VarNewTy04(GenTupStruct00000002),
    VarTuple05(u32, f64, i8, GenStruct00000001, ),
    VarTuple06(i16, u64, GenTupStruct00000003, ),
    VarTuple07(i16, ),
    VarEmpty08,
    VarStruct09 {
        field00: GenStruct00000000,
        field01: u32,
    },
    VarStruct0A {
        field00: i32,
    },
    VarEmpty0B,
    VarTuple0C(u16, i32, ),
    VarStruct0D {
        field00: bool,
        field01: GenTupStruct00000002,
        field02: GenTupStruct00000003,
    },
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000007 {
    VarNewTy00(GenEnum00000006),
    VarTuple01(GenEnum00000006, i8, GenStruct00000004, i64, ),
    VarNewTy02(u64),
    VarNewTy03(GenStruct00000001),
}

/// generated
type GenArray00000008 = [GenTupStruct00000003; 12];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000009 {
    VarStruct00 {
        field00: u128,
        field01: isize,
        field02: f32,
    },
    VarStruct01 {
        field00: usize,
    },
    VarEmpty02,
    VarNewTy03(i64),
    VarEmpty04,
    VarStruct05 {
        field00: GenArray00000008,
    },
    VarEmpty06,
    VarNewTy07(usize),
    VarEmpty08,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000000A;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000000B {
    VarTuple00(GenArray00000008, ),
    VarNewTy01(f32),
}

/// generated
type GenTup0000000C = (GenTupStruct00000003, GenStruct00000004, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000000D(u128, isize, GenStruct00000004, );

/// generated
type GenTup0000000E = (GenArray00000008, i128, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000000F {
    field00: GenArray00000008,
}

/// generated
type GenArray00000010 = [GenTupStruct00000002; 30];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000011 {
    VarEmpty00,
    VarTuple01(usize, ),
    VarTuple02(GenEnum00000009, GenEnum0000000B, i16, GenEnum0000000B, ),
    VarNewTy03(i32),
    VarTuple04(GenEnum00000006, i8, ),
    VarStruct05 {
        field00: GenTup0000000E,
        field01: u64,
        field02: GenTupStruct00000002,
        field03: i128,
    },
    VarStruct06 {
        field00: GenStruct00000004,
    },
    VarEmpty07,
    VarNewTy08(i8),
    VarNewTy09(GenTupStruct00000003),
}

/// generated
type GenOpt00000012 = Option<GenTupStruct0000000D>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000013(GenArray00000008, isize, GenOpt00000012, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000014(u64, GenOpt00000012, f32, i64, );

/// generated
type GenOpt00000015 = Option<f64>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000016(GenArray00000010, isize, u128, GenOpt00000012, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000017 {
    field00: GenOpt00000012,
    field01: u64,
    field02: GenArray00000008,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000018 {
    VarEmpty00,
    VarTuple01(GenTupStruct00000014, GenEnum00000007, ),
}

/// generated
type GenOpt00000019 = Option<f32>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000001A {
    field00: GenTupStruct00000013,
    field01: isize,
    field02: GenStruct00000001,
    field03: GenTupStruct00000014,
}

/// generated
type GenOpt0000001B = Option<GenTupStruct00000013>;

/// generated
type GenArray0000001C = [GenOpt00000019; 21];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000001D {
    VarEmpty00,
    VarStruct01 {
        field00: GenTupStruct00000003,
        field01: GenStruct0000000F,
        field02: GenEnum0000000B,
        field03: GenTup0000000C,
    },
    VarEmpty02,
    VarStruct03 {
        field00: GenEnum00000009,
        field01: GenStruct00000000,
        field02: GenArray00000010,
        field03: GenStruct00000004,
    },
    VarNewTy04(i128),
    VarEmpty05,
    VarTuple06(GenStruct0000001A, isize, ),
}

/// generated
type GenTup0000001E = (GenStruct00000000, GenArray00000008, GenArray00000008, GenStruct0000000A, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000001F {
    VarNewTy00(GenTup00000005),
    VarEmpty01,
    VarNewTy02(GenTupStruct00000014),
    VarStruct03 {
        field00: f64,
        field01: u16,
        field02: isize,
    },
    VarStruct04 {
        field00: GenStruct0000000F,
    },
    VarStruct05 {
        field00: u32,
        field01: GenTup0000000C,
        field02: i64,
    },
    VarStruct06 {
        field00: GenStruct00000001,
        field01: GenStruct00000000,
    },
    VarNewTy07(GenEnum00000006),
    VarTuple08(GenOpt0000001B, isize, GenEnum0000000B, GenStruct00000017, ),
    VarStruct09 {
        field00: GenEnum00000009,
        field01: u16,
        field02: GenTupStruct00000013,
    },
    VarTuple0A(f32, GenStruct0000000A, u64, u8, ),
    VarEmpty0B,
    VarStruct0C {
        field00: GenArray00000008,
    },
}

/// generated
type GenArray00000020 = [GenEnum0000001F; 21];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000021(bool, GenOpt0000001B, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000022 {
    field00: i64,
    field01: GenTupStruct00000016,
    field02: usize,
    field03: GenTupStruct00000014,
    field04: GenEnum00000006,
    field05: GenTupStruct00000002,
}

/// generated
type GenArray00000023 = [GenStruct00000000; 23];

/// generated
type GenArray00000024 = [GenStruct0000000A; 21];

/// generated
type GenTup00000025 = (GenArray00000020, GenOpt00000019, );

/// generated
type GenOpt00000026 = Option<GenEnum0000001F>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000027 {
    field00: GenEnum0000001F,
    field01: GenTup0000001E,
    field02: GenStruct00000004,
    field03: GenStruct0000000F,
    field04: GenEnum00000007,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000028 {
    VarTuple00(u64, GenEnum00000009, GenStruct00000017, GenOpt00000015, ),
    VarStruct01 {
        field00: GenEnum0000001D,
        field01: GenStruct00000017,
        field02: GenArray00000010,
        field03: GenStruct00000022,
    },
    VarStruct02 {
        field00: GenTupStruct00000014,
        field01: GenTupStruct00000002,
        field02: GenTup0000000E,
        field03: GenTupStruct00000013,
    },
    VarEmpty03,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000029 {
    VarStruct00 {
        field00: u16,
    },
    VarNewTy01(u8),
    VarEmpty02,
    VarTuple03(i8, GenEnum00000028, GenTup0000000C, ),
    VarNewTy04(GenStruct0000000A),
    VarNewTy05(GenStruct00000000),
    VarNewTy06(GenTupStruct00000003),
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000002A(i8, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000002B(GenOpt00000019, GenArray00000024, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000002C {
    VarEmpty00,
    VarNewTy01(GenEnum0000001F),
    VarEmpty02,
    VarEmpty03,
    VarStruct04 {
        field00: GenStruct00000000,
        field01: i8,
        field02: GenTupStruct0000002B,
        field03: i8,
    },
    VarTuple05(GenStruct00000017, GenStruct00000001, ),
    VarNewTy06(GenTupStruct0000002B),
    VarNewTy07(GenOpt00000026),
    VarStruct08 {
        field00: GenOpt0000001B,
    },
}

/// generated
type GenTup0000002D = (GenEnum00000007, GenTupStruct00000016, );

/// generated
type GenTup0000002E = (i32, GenTup0000001E, GenEnum0000001D, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000002F {
    VarEmpty00,
    VarNewTy01(GenTupStruct00000003),
    VarTuple02(GenStruct00000017, GenTup0000002E, i8, GenEnum00000006, ),
    VarNewTy03(u16),
    VarTuple04(GenTupStruct0000000D, ),
    VarTuple05(GenTup00000005, ),
    VarStruct06 {
        field00: u64,
        field01: GenArray00000020,
        field02: GenStruct00000000,
    },
    VarStruct07 {
        field00: i64,
        field01: GenStruct00000022,
        field02: i32,
        field03: GenEnum0000000B,
    },
    VarEmpty08,
    VarEmpty09,
    VarStruct0A {
        field00: GenTupStruct00000003,
        field01: GenEnum0000002C,
    },
    VarTuple0B(GenEnum00000011, GenStruct0000000F, ),
    VarTuple0C(GenEnum00000028, GenOpt0000001B, GenEnum00000011, ),
    VarTuple0D(GenEnum0000000B, GenTupStruct00000016, u128, ),
    VarTuple0E(GenTupStruct00000002, ),
    VarTuple0F(GenEnum00000029, GenOpt00000019, GenTupStruct00000013, ),
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000030 {
    field00: GenTup0000000C,
    field01: GenStruct0000001A,
    field02: GenArray00000020,
}

/// generated
type GenOpt00000031 = Option<GenStruct00000000>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000032(GenEnum00000018, f32, GenEnum0000000B, GenStruct0000001A, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000033 {
    VarStruct00 {
        field00: GenStruct00000001,
        field01: GenTup0000001E,
        field02: GenStruct00000000,
        field03: GenEnum00000029,
    },
    VarEmpty01,
    VarNewTy02(GenTupStruct0000002A),
    VarNewTy03(i32),
    VarTuple04(GenTup00000005, ),
    VarStruct05 {
        field00: usize,
        field01: GenEnum00000007,
        field02: GenTupStruct00000016,
    },
    VarStruct06 {
        field00: GenEnum00000011,
        field01: GenTup0000002D,
        field02: GenStruct00000001,
    },
    VarTuple07(i32, GenStruct0000000F, ),
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000034 {
    VarStruct00 {
        field00: GenEnum0000001F,
    },
    VarNewTy01(GenTupStruct0000000D),
    VarNewTy02(GenOpt00000015),
    VarStruct03 {
        field00: GenStruct0000000A,
        field01: i128,
        field02: GenStruct0000000F,
    },
    VarNewTy04(GenStruct00000001),
    VarEmpty05,
    VarNewTy06(u16),
    VarNewTy07(GenTup0000000C),
    VarEmpty08,
    VarTuple09(GenArray00000024, GenTup00000005, GenArray00000010, ),
    VarEmpty0A,
    VarEmpty0B,
    VarTuple0C(GenStruct00000017, GenStruct00000030, ),
    VarNewTy0D(GenArray00000024),
    VarStruct0E {
        field00: GenTup00000025,
        field01: GenArray00000024,
    },
}

/// generated
type GenOpt00000035 = Option<GenTupStruct0000002A>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000036(u32, GenTupStruct00000021, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000037 {
    VarStruct00 {
        field00: GenStruct00000017,
        field01: i32,
        field02: GenTupStruct00000036,
    },
    VarStruct01 {
        field00: GenOpt00000012,
    },
    VarEmpty02,
    VarStruct03 {
        field00: GenTupStruct00000032,
    },
    VarTuple04(GenEnum00000011, ),
    VarNewTy05(GenTupStruct00000013),
    VarNewTy06(GenOpt00000015),
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000038 {
    VarNewTy00(bool),
    VarNewTy01(i64),
    VarNewTy02(GenEnum00000011),
    VarStruct03 {
        field00: GenTupStruct00000036,
    },
    VarEmpty04,
    VarNewTy05(GenOpt0000001B),
    VarStruct06 {
        field00: GenEnum00000011,
        field01: GenOpt00000031,
    },
    VarEmpty07,
    VarNewTy08(GenStruct00000004),
    VarTuple09(GenEnum00000006, GenEnum0000001F, ),
    VarStruct0A {
        field00: u64,
        field01: GenTupStruct0000000D,
    },
    VarStruct0B {
        field00: GenOpt00000035,
    },
    VarEmpty0C,
    VarNewTy0D(GenTup00000025),
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000039 {
    field00: GenEnum00000028,
    field01: GenEnum00000006,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000003A {
    field00: i8,
}

/// generated
type GenTup0000003B = (GenEnum00000033, GenEnum00000007, GenTupStruct00000014, GenStruct0000000A, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000003C {
    VarTuple00(i128, ),
    VarEmpty01,
    VarNewTy02(GenTupStruct0000000D),
    VarStruct03 {
        field00: GenStruct00000017,
        field01: GenTupStruct00000003,
        field02: GenStruct0000000F,
    },
    VarEmpty04,
}

/// generated
type GenArray0000003D = [GenEnum00000033; 30];

/// generated
type GenOpt0000003E = Option<GenArray00000008>;

/// generated
type GenTup0000003F = (GenTup0000002D, GenEnum00000006, usize, GenOpt0000001B, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000040 {
    field00: GenStruct0000000A,
    field01: GenEnum00000028,
    field02: GenTup0000000E,
    field03: GenTupStruct0000002B,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000041 {
    field00: GenStruct0000000F,
    field01: u128,
    field02: GenTup0000000E,
    field03: GenStruct0000003A,
    field04: GenEnum0000003C,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000042 {
    field00: GenTup00000025,
    field01: GenTup0000003B,
    field02: GenTupStruct00000016,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000043 {
    VarEmpty00,
    VarStruct01 {
        field00: GenStruct00000042,
    },
    VarEmpty02,
    VarEmpty03,
    VarEmpty04,
    VarNewTy05(GenEnum0000002C),
    VarEmpty06,
    VarNewTy07(GenTupStruct00000016),
    VarStruct08 {
        field00: GenTup0000002E,
        field01: GenTupStruct00000032,
        field02: GenTupStruct00000036,
    },
    VarTuple09(GenOpt00000012, GenEnum00000018, i16, ),
    VarNewTy0A(GenArray00000024),
    VarTuple0B(GenEnum00000037, GenEnum00000007, ),
    VarStruct0C {
        field00: GenOpt00000035,
        field01: GenOpt0000003E,
        field02: GenEnum0000001F,
        field03: GenEnum0000001F,
    },
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000044 {
    field00: GenArray0000001C,
    field01: u8,
    field02: GenOpt00000035,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000045 {
    field00: GenOpt0000001B,
    field01: GenTupStruct00000032,
    field02: f32,
    field03: GenStruct00000030,
    field04: GenTup0000001E,
    field05: GenTupStruct0000000D,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000046 {
    VarStruct00 {
        field00: u16,
        field01: GenStruct00000017,
    },
}

/// generated
type GenTup00000047 = (GenTupStruct00000021, GenTupStruct00000021, u32, GenArray00000023, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000048(GenEnum00000006, GenTup0000001E, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000049 {
    VarTuple00(GenTup00000047, ),
    VarNewTy01(GenEnum00000034),
    VarEmpty02,
    VarStruct03 {
        field00: u32,
    },
    VarStruct04 {
        field00: GenOpt00000015,
        field01: i32,
    },
    VarEmpty05,
    VarTuple06(u16, GenTupStruct00000036, GenEnum00000037, GenTupStruct00000021, ),
    VarNewTy07(f32),
    VarStruct08 {
        field00: GenEnum00000006,
        field01: GenEnum0000003C,
    },
    VarTuple09(i8, GenStruct00000041, GenStruct00000044, GenEnum00000046, ),
    VarEmpty0A,
}

/// generated
type GenArray0000004A = [GenEnum00000037; 5];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000004B {
    field00: GenStruct00000039,
    field01: GenStruct00000017,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000004C(GenEnum00000009, bool, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000004D(GenEnum00000049, GenEnum00000028, GenEnum00000046, );

/// generated
type GenArray0000004E = [GenOpt00000015; 12];

/// generated
type GenTup0000004F = (u8, GenOpt00000035, GenTup0000002D, i64, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000050;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000051(GenEnum0000001F, GenArray00000020, GenTup0000002E, GenTupStruct00000048, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000052(isize, GenEnum00000028, u64, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000053 {
    VarEmpty00,
    VarStruct01 {
        field00: GenEnum00000011,
        field01: GenTup0000000C,
        field02: GenOpt00000012,
    },
    VarNewTy02(GenStruct00000027),
    VarEmpty03,
    VarStruct04 {
        field00: GenEnum00000018,
        field01: GenStruct0000001A,
    },
    VarNewTy05(GenStruct0000001A),
    VarTuple06(GenEnum0000002F, GenTupStruct00000013, GenStruct0000003A, ),
    VarNewTy07(GenOpt00000012),
}

/// generated
type GenTup00000054 = (GenEnum0000000B, u64, GenOpt00000035, GenEnum00000018, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000055 {
    VarStruct00 {
        field00: GenStruct00000027,
    },
    VarEmpty01,
    VarEmpty02,
    VarEmpty03,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000056(GenTupStruct00000021, GenTupStruct00000036, u64, );

/// generated
type GenOpt00000057 = Option<GenStruct00000004>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000058 {
    field00: GenArray0000004E,
}

/// generated
type GenArray00000059 = [f32; 11];

/// generated
type GenArray0000005A = [GenTupStruct00000036; 32];

/// generated
type GenOpt0000005B = Option<GenArray00000008>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000005C {
    field00: GenEnum00000007,
    field01: GenTup0000004F,
    field02: GenTup0000002D,
    field03: GenEnum00000053,
    field04: GenTupStruct00000051,
    field05: bool,
    field06: GenTupStruct00000032,
}

/// generated
type GenOpt0000005D = Option<GenEnum00000009>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000005E {
    VarStruct00 {
        field00: GenTupStruct00000032,
        field01: GenStruct00000022,
        field02: GenTupStruct00000051,
        field03: GenEnum00000028,
    },
    VarStruct01 {
        field00: GenTupStruct00000036,
        field01: i64,
        field02: GenTup00000005,
    },
    VarEmpty02,
    VarEmpty03,
    VarStruct04 {
        field00: GenEnum0000002C,
        field01: GenEnum00000011,
        field02: GenTup00000025,
    },
    VarTuple05(GenArray00000059, GenOpt00000031, ),
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000005F;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000060 {
    VarStruct00 {
        field00: GenTupStruct00000016,
    },
    VarStruct01 {
        field00: GenEnum00000038,
        field01: GenStruct00000040,
        field02: GenEnum0000001D,
    },
    VarTuple02(GenArray00000008, GenEnum00000018, GenOpt0000005D, ),
    VarTuple03(GenEnum00000018, GenEnum0000003C, i32, GenTupStruct00000021, ),
    VarStruct04 {
        field00: GenTupStruct00000048,
        field01: GenArray00000024,
        field02: GenTupStruct0000000D,
    },
    VarTuple05(GenTup0000000E, GenStruct00000017, ),
}

/// generated
type GenArray00000061 = [GenStruct0000005F; 26];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000062 {
    field00: GenTupStruct00000052,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000063 {
    VarStruct00 {
        field00: GenStruct0000005C,
        field01: GenTup0000003B,
        field02: GenTup0000004F,
        field03: GenArray00000010,
    },
    VarNewTy01(GenEnum00000038),
    VarNewTy02(GenTupStruct0000004C),
    VarTuple03(GenStruct00000062, GenArray00000059, i32, ),
    VarStruct04 {
        field00: GenEnum00000034,
        field01: GenEnum0000002F,
    },
    VarTuple05(GenStruct0000005F, GenStruct00000001, GenEnum00000028, ),
    VarNewTy06(GenTup0000004F),
    VarEmpty07,
    VarEmpty08,
    VarNewTy09(GenEnum0000002F),
    VarTuple0A(GenTupStruct00000014, GenTupStruct00000016, ),
    VarTuple0B(GenEnum00000029, GenStruct00000000, GenArray00000024, ),
    VarTuple0C(GenArray00000023, GenOpt00000031, ),
    VarNewTy0D(GenStruct00000039),
    VarEmpty0E,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000064 {
    field00: GenArray00000059,
    field01: i16,
}

/// generated
type GenTup00000065 = (GenStruct00000022, GenOpt0000003E, );

/// generated
type GenTup00000066 = (GenArray00000024, GenOpt00000031, GenTupStruct0000002B, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000067 {
    field00: GenTupStruct0000004D,
    field01: GenEnum00000046,
    field02: GenTup0000000C,
    field03: GenTupStruct00000021,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000068(GenTupStruct00000032, usize, f32, GenEnum00000033, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000069 {
    VarStruct00 {
        field00: GenTup0000003F,
        field01: GenStruct00000027,
        field02: isize,
        field03: GenOpt00000026,
    },
    VarStruct01 {
        field00: GenOpt00000015,
        field01: GenTup0000003F,
        field02: GenEnum00000007,
        field03: u32,
    },
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000006A(i16, GenOpt0000003E, GenArray00000059, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000006B {
    field00: GenTupStruct0000000D,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000006C {
    field00: GenTupStruct00000003,
    field01: GenStruct00000000,
    field02: GenStruct00000027,
    field03: GenStruct0000005F,
    field04: GenTupStruct0000004C,
}

/// generated
type GenTup0000006D = (GenStruct00000067, GenArray00000061, GenArray0000001C, );

/// generated
type GenOpt0000006E = Option<i32>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000006F(GenStruct0000000A, );

/// generated
type GenTup00000070 = (GenOpt0000005D, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000071 {
    VarTuple00(GenEnum00000038, GenEnum0000005E, GenEnum0000002C, GenEnum00000006, ),
    VarNewTy01(i32),
    VarNewTy02(GenStruct0000000A),
    VarEmpty03,
    VarTuple04(GenTupStruct0000002B, GenStruct0000003A, u128, GenTup00000065, ),
    VarEmpty05,
    VarTuple06(GenOpt0000005D, GenTupStruct0000002A, ),
    VarEmpty07,
    VarEmpty08,
    VarEmpty09,
    VarNewTy0A(GenTupStruct0000004C),
    VarEmpty0B,
    VarNewTy0C(GenTup0000000E),
    VarEmpty0D,
    VarStruct0E {
        field00: GenOpt00000057,
    },
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct00000072(GenStruct0000003A, GenEnum00000011, GenTupStruct00000056, GenArray0000004E, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000073 {
    field00: GenTupStruct00000002,
    field01: i16,
    field02: GenEnum00000053,
    field03: GenEnum00000060,
    field04: GenArray00000061,
}

/// generated
type GenOpt00000074 = Option<GenEnum00000028>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum00000075 {
    VarNewTy00(GenArray0000001C),
    VarEmpty01,
    VarNewTy02(GenStruct0000003A),
    VarNewTy03(GenEnum00000037),
    VarStruct04 {
        field00: GenStruct0000001A,
        field01: GenTup00000054,
        field02: GenTupStruct0000006F,
        field03: GenTup0000002E,
    },
    VarStruct05 {
        field00: GenArray0000001C,
        field01: GenTup00000025,
    },
    VarNewTy06(GenEnum00000071),
    VarEmpty07,
    VarEmpty08,
    VarTuple09(GenTup0000002D, GenOpt0000005D, GenEnum00000049, ),
    VarNewTy0A(GenStruct00000027),
    VarNewTy0B(GenEnum00000043),
    VarEmpty0C,
}

/// generated
type GenArray00000076 = [GenEnum0000000B; 10];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000077 {
    field00: GenTupStruct0000000D,
    field01: GenStruct00000022,
    field02: GenOpt0000005D,
    field03: GenTup0000001E,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000078 {
    field00: GenEnum00000006,
    field01: GenStruct00000040,
    field02: usize,
    field03: u32,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct00000079 {
    field00: GenStruct0000006B,
}

/// generated
type GenOpt0000007A = Option<GenTup0000001E>;

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenStruct0000007B {
    field00: GenTupStruct00000052,
}

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
struct GenTupStruct0000007C(GenTup00000025, GenEnum00000053, );

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000007D {
    VarTuple00(u128, GenEnum0000002C, GenEnum00000006, GenEnum00000029, ),
    VarNewTy01(GenStruct00000050),
    VarTuple02(GenTupStruct00000013, i16, GenEnum00000006, i128, ),
    VarStruct03 {
        field00: GenEnum00000049,
        field01: GenStruct00000078,
        field02: GenTupStruct0000004D,
        field03: GenTup0000000E,
    },
    VarEmpty04,
    VarNewTy05(GenEnum00000037),
    VarStruct06 {
        field00: GenArray00000024,
    },
    VarNewTy07(GenTupStruct0000004C),
    VarEmpty08,
    VarEmpty09,
    VarEmpty0A,
    VarTuple0B(GenEnum00000033, i8, ),
    VarTuple0C(GenStruct0000000F, GenOpt00000031, GenTupStruct0000004C, GenEnum00000018, ),
}

/// generated
type GenArray0000007E = [GenOpt0000007A; 16];

/// generated
#[derive(Debug)]
#[cfg_attr(feature = "serde", derive(::serde::Serialize, ::serde::Deserialize))]
#[cfg_attr(feature = "postcard-forth", derive(::postcard_forth_derive::Serialize, ::postcard_forth_derive::Deserialize))]
enum GenEnum0000007F {
    VarStruct00 {
        field00: GenTupStruct00000003,
        field01: GenTup0000001E,
        field02: GenStruct00000027,
    },
    VarTuple01(GenArray0000003D, GenStruct0000000F, ),
    VarStruct02 {
        field00: f64,
        field01: GenEnum00000018,
        field02: GenArray00000059,
    },
    VarNewTy03(GenTup00000005),
    VarNewTy04(GenTupStruct0000004D),
    VarTuple05(GenEnum00000053, GenEnum00000060, i32, ),
    VarNewTy06(GenTup0000002D),
    VarNewTy07(GenTupStruct0000004D),
    VarNewTy08(GenEnum00000028),
    VarNewTy09(GenTup00000066),
    VarEmpty0A,
    VarStruct0B {
        field00: GenOpt0000001B,
    },
    VarTuple0C(GenEnum00000075, GenStruct00000044, GenOpt00000031, GenTup0000002E, ),
    VarTuple0D(GenEnum00000049, GenEnum00000007, ),
    VarEmpty0E,
}


use core::fmt::Write;

struct SliceWrite<'a> {
    remain: &'a mut [u8],
    used: usize
}

impl<'a> Write for SliceWrite<'a> {
    #[inline]
    fn write_str(&mut self, s: &str) -> Result<(), core::fmt::Error> {
        let slen = s.len();
        if slen > self.remain.len() {
            return Err(core::fmt::Error);
        }
        let rem = core::mem::take(&mut self.remain);
        let (now, later) = rem.split_at_mut(slen);
        now.copy_from_slice(s.as_bytes());
        self.remain = later;
        self.used += slen;
        Ok(())
    }
}

#[inline]
pub(crate) fn debug<T: core::fmt::Debug>(
    t: &T,
    out_buf: &mut [u8],
) -> Result<usize, ()> {
    let mut sw = SliceWrite { remain: out_buf, used: 0 };
    write!(&mut sw, "{t:?}").map_err(drop)?;
    Ok(sw.used)
}

#[cfg(feature = "serde")]
#[inline]
fn deserialize<T: ::serde::de::DeserializeOwned>(
    in_buf: &[u8],
) -> Result<T, ()> {
    ::postcard::from_bytes::<T>(in_buf).map_err(drop)
}

#[cfg(feature = "postcard-forth")]
#[inline]
fn deserialize<T: ::postcard_forth::Deserialize>(
    in_buf: &[u8],
) -> Result<T, ()> {
    let mut desers = ::postcard_forth::DeserStream::from(in_buf);
    let mut out = core::mem::MaybeUninit::<T>::uninit();
    unsafe {
        ::postcard_forth::deser_fields_ref(&mut desers, &mut out).map_err(drop)?;
    }
    Ok(unsafe { out.assume_init() })
}

#[cfg(feature = "serde")]
#[inline]
fn serialize<T: ::serde::Serialize>(
    t: &T,
    out_buf: &mut [u8],
) -> Result<usize, ()> {
    ::postcard::to_slice(t, out_buf).map_err(drop).map(|u| u.len())
}

#[cfg(feature = "postcard-forth")]
#[inline]
fn serialize<T: ::postcard_forth::Serialize>(
    t: &T,
    out_buf: &mut [u8],
) -> Result<usize, ()> {
    let olen = out_buf.len();
    let mut sers = ::postcard_forth::SerStream::from(out_buf);
    unsafe {
        ::postcard_forth::ser_fields_ref(&mut sers, t).map_err(drop)?;
    }
    let remain = sers.remain();
    let used = olen - remain;
    Ok(used)
}

    

pub(crate) fn round_trip_all<FI, FD, FO>(
    in_buf: &mut [u8],
    out_buf: &mut [u8],
    mut recv_fn: FI,
    debg_fn: FD,
    send_fn: FO,
) -> Result<(), ()>
where
    FI: FnMut(&mut [u8]),
    FD: Fn(&[u8]),
    FO: Fn(&[u8]),
{
    

    {
        recv_fn(in_buf);
        let t: GenStruct00000000 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000000>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000001 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000001>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000002 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000002>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000003 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000003>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000004 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000004>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000005 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000005>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000006 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000006>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000007 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000007>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000008 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000008>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000009 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000009>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000000A = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000000A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000000B = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000000B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000000C = deserialize(in_buf)?;
        // let len = debug::<GenTup0000000C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000000D = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000000D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000000E = deserialize(in_buf)?;
        // let len = debug::<GenTup0000000E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000000F = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000000F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000010 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000010>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000011 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000011>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000012 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000012>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000013 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000013>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000014 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000014>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000015 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000015>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000016 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000016>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000017 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000017>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000018 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000018>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000019 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000019>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000001A = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000001A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt0000001B = deserialize(in_buf)?;
        // let len = debug::<GenOpt0000001B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray0000001C = deserialize(in_buf)?;
        // let len = debug::<GenArray0000001C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000001D = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000001D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000001E = deserialize(in_buf)?;
        // let len = debug::<GenTup0000001E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000001F = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000001F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000020 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000020>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000021 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000021>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000022 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000022>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000023 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000023>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000024 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000024>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000025 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000025>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000026 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000026>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000027 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000027>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000028 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000028>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000029 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000029>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000002A = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000002A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000002B = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000002B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000002C = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000002C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000002D = deserialize(in_buf)?;
        // let len = debug::<GenTup0000002D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000002E = deserialize(in_buf)?;
        // let len = debug::<GenTup0000002E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000002F = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000002F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000030 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000030>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000031 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000031>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000032 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000032>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000033 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000033>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000034 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000034>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000035 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000035>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000036 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000036>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000037 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000037>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000038 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000038>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000039 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000039>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000003A = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000003A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000003B = deserialize(in_buf)?;
        // let len = debug::<GenTup0000003B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000003C = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000003C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray0000003D = deserialize(in_buf)?;
        // let len = debug::<GenArray0000003D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt0000003E = deserialize(in_buf)?;
        // let len = debug::<GenOpt0000003E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000003F = deserialize(in_buf)?;
        // let len = debug::<GenTup0000003F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000040 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000040>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000041 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000041>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000042 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000042>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000043 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000043>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000044 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000044>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000045 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000045>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000046 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000046>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000047 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000047>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000048 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000048>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000049 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000049>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray0000004A = deserialize(in_buf)?;
        // let len = debug::<GenArray0000004A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000004B = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000004B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000004C = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000004C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000004D = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000004D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray0000004E = deserialize(in_buf)?;
        // let len = debug::<GenArray0000004E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000004F = deserialize(in_buf)?;
        // let len = debug::<GenTup0000004F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000050 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000050>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000051 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000051>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000052 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000052>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000053 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000053>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000054 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000054>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000055 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000055>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000056 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000056>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000057 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000057>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000058 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000058>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000059 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000059>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray0000005A = deserialize(in_buf)?;
        // let len = debug::<GenArray0000005A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt0000005B = deserialize(in_buf)?;
        // let len = debug::<GenOpt0000005B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000005C = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000005C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt0000005D = deserialize(in_buf)?;
        // let len = debug::<GenOpt0000005D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000005E = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000005E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000005F = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000005F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000060 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000060>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000061 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000061>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000062 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000062>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000063 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000063>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000064 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000064>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000065 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000065>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000066 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000066>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000067 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000067>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000068 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000068>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000069 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000069>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000006A = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000006A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000006B = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000006B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000006C = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000006C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup0000006D = deserialize(in_buf)?;
        // let len = debug::<GenTup0000006D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt0000006E = deserialize(in_buf)?;
        // let len = debug::<GenOpt0000006E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000006F = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000006F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTup00000070 = deserialize(in_buf)?;
        // let len = debug::<GenTup00000070>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000071 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000071>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct00000072 = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct00000072>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000073 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000073>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt00000074 = deserialize(in_buf)?;
        // let len = debug::<GenOpt00000074>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum00000075 = deserialize(in_buf)?;
        // let len = debug::<GenEnum00000075>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray00000076 = deserialize(in_buf)?;
        // let len = debug::<GenArray00000076>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000077 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000077>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000078 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000078>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct00000079 = deserialize(in_buf)?;
        // let len = debug::<GenStruct00000079>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenOpt0000007A = deserialize(in_buf)?;
        // let len = debug::<GenOpt0000007A>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenStruct0000007B = deserialize(in_buf)?;
        // let len = debug::<GenStruct0000007B>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenTupStruct0000007C = deserialize(in_buf)?;
        // let len = debug::<GenTupStruct0000007C>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000007D = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000007D>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenArray0000007E = deserialize(in_buf)?;
        // let len = debug::<GenArray0000007E>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        

    {
        recv_fn(in_buf);
        let t: GenEnum0000007F = deserialize(in_buf)?;
        // let len = debug::<GenEnum0000007F>(&t, out_buf)?;
        // debg_fn(&out_buf[..len]);
        let len = serialize(&t, out_buf)?;
        send_fn(&out_buf[..len]);
    }
        
    Ok(())
}
